### ISSUE TITLE
Eval ignoring child db argument

### ISSUE THREAD

**Issue by rachaelmcq** [fauna/fauna-shell#108]
Hello! I'm having trouble doing an `eval` on a child DB: 
```
yarn fauna eval childDB "Paginate(Collections())"
›   Error: Unexpected argument: Paginate(Collections())
```
This is the command from the doc. Eval works fine without the child db arg.  Any ideas?

**Comment by fireridlle** [comment]
@rachaelmcq this haven't been released yet

**Comment by rachaelmcq** [comment]
Thanks! FYI if it's relevant, I pulled down https://github.com/fauna/fauna-shell/pull/106 and `fauna eval childDB "Paginate(Collections())"` works now, but `fauna eval child --file=[...].fql` doesn't. Good luck with release!
