### ISSUE TITLE
fauna cloud-login error in 0.12.5

### ISSUE THREAD

**Issue by hirnidrin** [fauna/fauna-shell#121]
Ubuntu LTS 18.04
After update from fauna-shell 0.12.4 to 0.12.5, fauna cloud-login returns
**SyntaxError: Unexpected token < in JSON at position 1**
Rollback to 0.12.4 -> works ok.

```
fauna --version
fauna-shell/0.12.5 linux-x64 node-v14.17.6

fauna cloud-login
? The endpoint alias prefix (to combine with a region): cloud
? The endpoint alias already exists. Overwrite? Yes
? How do you prefer to authenticate? Email and Password
? Email address: [redacted]
? Password: [hidden]
    SyntaxError: Unexpected token < in JSON at position 1
```

**Comment by fireridlle** [comment]
hi @hirnidrin . could you please clarify your regular login flow at the browser? does 2fa enabled? anything else?

**Comment by hirnidrin** [comment]
Thanks for inquiring. I use normal email/pass auth, without 2FA.
I just updated fauna-shell from 0.12.4 to 0.12.6 -> now cloud-login works fine. I won't dig into the 0.12.5 problem again, is/was maybe a local issue on my VM. For me, case closed.
Thanks and best regards.
