### ISSUE TITLE
upload-graphql-schema command prints "RESPONSE: undefined"

### ISSUE THREAD

**Issue by ptpaterson** [fauna/fauna-shell#133]
# Problem

running `fauna upload-graphql-schema` prints "RESPONSE: undefined" in the console.  The schema is successfully uploaded, but this console output is very confusing.  I'm not sure what should be returned instead.

# Env

```bash
> fauna --version

fauna-shell/0.12.6 darwin-x64 node-v16.11.1
```

# Steps to reproduce

log in to a database.  I used a secret key, rather than email+password.

```bash
> fauna cloud-login
```

once logged in, run the command

```bash
> fauna upload-graphql-schema ./schema.gql
UPLOADING SCHEMA (mode=merge): ./schema.gql
RESPONSE:
undefined
```

**Comment by fireridlle** [comment]
not related to the shell

**Comment by ptpaterson** [comment]
For the history, this was related to a change made to use request-promise.  #135 fixed this issue
