### ISSUE TITLE
cloud-login --github not working 

### ISSUE THREAD

**Issue by chandu0101** [fauna/fauna-shell#19]
when i tried to login using github `fauna cloud-login --github` , callback url [https://auth.console.fauna.com/oauth/callback](https://auth.console.fauna.com/oauth/callback) returning 500

**Comment by BrunoQuaresma** [comment]
Hey @chandu0101, we disabled this feature for now but, you should be able to use fauna-shell generating a secret through the web dashboard. We updated the fauna-shell (0.9.8) to make this flow easier. Let me know if you have any issues to get this working.
