### ISSUE TITLE
Importing a large dataset with unique Index constraints results in missing documents

### ISSUE THREAD

**Issue by njbmartin** [fauna/fauna-shell#197]
I have created a collection to store all my data (88k rows), which has MANY duplicate entries. I originally imported them all, but want to ensure that only unique rows are stored so I used an Index to create a Unique field and started with a fresh collection again, but when I import, I get the following _expected_ error:

```sh
Warning: item numbers: 54819,54820,54821,54822 (zero-indexed) in your input file './imports/streamers.csv' failed to persist in Fauna due to: 'document is not unique.' - Continuing ...
```

Then this is the end result:
```sh
62158 rows/object failed to import. 26787 rows/object succeeded.
```

This is understandable as I would expect it to skip over any duplicates, but the rows succeeded seems awfully low. When I then query the Index after import, the document doesn't exist. I've done about 10 different searches at random, and only 2 results came back.

I reran the import with `--append`, and got **88742 rows/object failed to import. 203 rows/object succeeded**, so it seems to be an issue with duplicate rows in the same batch?

**Comment by cleve-fauna** [comment]
Hey @njbmartin sorry it took so long to get back to you.

Do you know how many unique values you have in your file? Like what number would you expect to see for an import and what number do you expect to fail?

Also, you are correct in inferring that the data gets written in batches. So if one item is invalid in the batch the whole batch will fail.

If you're willing to share your file I'd be happy to try it locally and see what's going on in more detail.

**Comment by cleve-fauna** [comment]
Another approach you might take if you don't want to wait is to do the following:

- import to a place with no unique index
- build an index on the field that should be unique - but don't make it unique yet
- write a script that deletes all but one of each of those
- replace the index with a unique index

Alternatively, you may be able to use some scripting in your language of choice to reduce your input file to a unique set of inputs.

**Comment by cleve-fauna** [comment]
Hey @njbmartin please reopen if you need more assistance.
