### ISSUE TITLE
Batch delete

### ISSUE THREAD

**Issue by abtx** [fauna/fauna-shell#27]
Hi, thanks for making `fauna-shell` for us. 

A batch delete doesn't seem to be in `fauna-shell` and is not available in the web dashboard either, so I'm finding myself writing UI that fetches the data and iterates over all items in a collection should I want to clean it. 

If there was a delete that could accept a wildcard in development mode that'd be awesome, or a way to drop entire collection.

Cheers!

**Comment by n400** [comment]
Hi @abtx this feature would need to be added to the core API and not in the fauna-shell, so I am going to close this issue for now. Please make a feature request on https://forums.fauna.com/c/feature-requests/2
