### ISSUE TITLE
You need to update the sample codes. Sample codes don't work

### ISSUE THREAD

**Issue by bulentala** [fauna/fauna-shell#34]
my_app> CreateClass({ name: "posts" })
{ ref: Class("posts"),
  ts: 1532624109799742,
  history_days: 30,
  name: 'posts' }
------------------
CreateCollection({ name: "posts" })
{ ref: Collection("posts"),
  ts: 1532624109799742,
  history_days: 30,
  name: 'posts' }

**Comment by n400** [comment]
Yes, Classes were renamed to Collections in 2.7. I only found CreateClass in docs/dev.md and made a PR to fix it: https://github.com/fauna/fauna-shell/pull/89
But I could not find this specific code. Where in the repo did you find this specific example?
