### ISSUE TITLE
fauna list-keys crashes

### ISSUE THREAD

**Issue by djdiaz** [fauna/fauna-shell#59]
Running `fauna list-keys` crashes with:
```
Error: Cannot read property 'id' of undefined
```

Fauna shell version:
```
fauna-shell/0.11.5 darwin-x64 node-v12.16.2
```

**Comment by evbruno** [comment]
@djdiaz Is `fauna list-databases` working for you ?

**Comment by djdiaz** [comment]
Yes, `list-databases` works properly.

**Comment by fireridlle** [comment]
@djdiaz can you please try with latest version?

**Comment by fireridlle** [comment]
issue closed as stale
