### ISSUE TITLE
Upload schema from the shell

### ISSUE THREAD

**Issue by JerryGreen** [fauna/fauna-shell#67]
I don't see there such a command, but I'd like to be able to upload with with the cli.

There's already some work done on VSCode extension side:

https://github.com/fauna/vscode/blob/8a409be6e38544c316ea1bf8c4ba6ed24cd4d5b0/src/uploadGraphqlSchemaCommand.ts

**Comment by Zhouzi** [comment]
I'd also be interested in this feature 👍 What I'm trying to do is to keep the schema with the rest of the code and have it deployed automatically.

Meanwhile, this project looks promising: [ptpaterson/faunadb-graphql-schema-loader](https://github.com/ptpaterson/faunadb-graphql-schema-loader)
