### ISSUE TITLE
create-key should return its name

### ISSUE THREAD

**Issue by JerryGreen** [fauna/fauna-shell#70]
In addition to the value, the response should also return its name (so it will be possible to cache it for delete command)

Also won't be needed to make yet another request to list-keys (which are broken btw: https://github.com/fauna/fauna-shell/issues/68)

**Comment by fireridlle** [comment]
do you mean `ref`? `CreateKey` command doesn't have `name` field at the response

**Comment by JerryGreen** [comment]
It's half a year already... Anyway, if I remember properly, `fauna crate-key` doesn't return enough information for `fauna delete-key` though it kinda looks like it isn't true to me currently, so I may simply misunderstood something back then. I don't use this tool anymore, to help you re-check everything, sorry

**Comment by fireridlle** [comment]
close this issue as stale.
